In [25]:
import numpy as np

## Numpy array and basics

In [26]:
## creating array from list


arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [27]:
import time

py_list = [1,2,3,4]
print("Python list Multiplication: ", py_list * 2)

np_array = np.array([1,2,3,4,5])
print("Python array Multiplication: ", np_array * 2)

start1 = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start1)

start2 = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start2)


Python list Multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Python array Multiplication:  [ 2  4  6  8 10]

 List operation time:  0.18189287185668945

 Numpy operation time:  0.014862060546875


## Creating array from scratch

In [28]:
zeros = np.zeros((3,2))
print('zero array: \n', zeros)

ones = np.ones((2,4))
print('ones array: \n', ones)

full = np.full((2,3), 8)
print('full array: \n', full)

random = np.random.random((2,2))
print('random array: \n', random)

sequence = np.arange(0, 10, 2)
print('sequence array: \n', sequence)

zero array: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[8 8 8]
 [8 8 8]]
random array: 
 [[0.22686433 0.63259687]
 [0.45367574 0.7342929 ]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [29]:
vector = np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print('Tensor: ', tensor)

vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [30]:
arr = np.array([
    [1,2,3.8],
    [4,5,6]
])
print("shape of array: ", arr.shape)
print("dimension of array: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

shape of array:  (2, 3)
dimension of array:  2
Size:  6
Dtype:  float64


## Array Reshaping

In [31]:
arr = np.arange(12)
print("original array: ", arr)

reshaped = arr.reshape((3, 4))
print('\n Reshaped array', reshaped)

flattend = reshaped.flatten()
print('\n flattend array', flattend)

# it return view instead of copy
raveled = reshaped.ravel()
print('\n raveled', raveled)

#Transpose
transpose = reshaped.T
print('\n transpose', transpose)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Array Operations

In [32]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,12])
print('Basic slicing: ', arr_1d[2:8]) #slicing
print("With step: ", arr_1d[2:7:1])
print("Negative indexing: ", arr_1d[-2])


Basic slicing:  [3 4 5 6 7 8]
With step:  [3 4 5 6 7]
Negative indexing:  9


In [33]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


## Sorting

In [34]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

# axis 0 is used for columns and axis 1 is used for rows
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by rows", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by rows [[1 3]
 [1 2]
 [2 3]]


## Filter

In [35]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [36]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [37]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


## Adding and removing data

In [38]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## array compatibility

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [40]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [41]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
